// AUTO-GENERATED by pcibex/tools/prepare_stimuli.py from
// data/training_frame.md. Do not hand-edit -- change the prose there
// and re-run prepare_stimuli.py (--reuse-timings is enough), then build.py.
//
// One entry per screen, one string per paragraph, in order.
window.EXP2_TRAINING_FRAME = {
  "closing": [
    "I dialoghi di prova sono finiti. Ora inizia l'esperimento vero e proprio: da qui in poi non riceverai più indicazioni su come valutare le risposte.",
    "Alcune risposte ti sembreranno chiaramente accettabili o inaccettabili, ma per altre potresti voler dare una valutazione intermedia. Usa pure tutto l'intervallo del cursore, non solo i due estremi."
  ],
  "opening": [
    "Prima di cominciare l'esperimento vero e proprio, ti verranno mostrati <b>6 dialoghi di prova</b>. Servono per fare un po' di pratica.",
    "Dopo aver ascoltato ogni dialogo di prova, un riquadro ti spiegherà come valutare la risposta. Leggilo con attenzione prima di usare il cursore.",
    "Puoi ascoltare ogni dialogo al massimo due volte."
  ]
};
