// AUTO-GENERATED by `design/generate.py` from design/design.toml.
// Do not hand-edit -- change the declaration and regenerate.

window.EXP2_DESIGN = {
  factors: {
    phase: { levels: ["pretest", "test"], raw: { "pretest": "pretest", "test": "test" } },
    subexp: { levels: ["sm", "or", "wh"], raw: { "sm": "sm", "or": "or", "wh": "wh" } },
    cond_question: { levels: ["all", "no", "wh", "pos", "neg"], raw: { "all": "all", "no": "no", "wh": "wh", "pos": "pos", "neg": "neg" } },
    cond_answer: { levels: ["all", "no", "wh", "impl", "canc", "ign", "pos", "neg"], raw: { "all": "all", "no": "no", "wh": "wh", "impl": "impl", "canc": "canc", "ign": "ign", "pos": "pos", "neg": "neg" } },
    group: { levels: ["a", "b", "c", "d"], raw: { "a": "a", "b": "b", "c": "c", "d": "d" } },
    split: { levels: ["whole", "sm", "or"], raw: { "whole": "whole", "sm": "sm", "or": "or" } },
    continuations: { levels: ["on", "off"], raw: { "on": "on", "off": "off" } }
  },
  columns: {
    item: ["subexp", "condition", "cond_question", "cond_answer", "num", "kid", "group", "context", "request", "question", "answer", "continuation", "audio", "q_start_ms", "q_end_ms", "a_start_ms", "a_end_ms", "total_ms", "c_start_ms", "audio_nocont", "total_ms_nocont"],
    results: ["session_id", "phase", "split", "continuations", "group", "trial_index", "training_item", "subexp", "condition", "cond_question", "cond_answer", "num", "kid", "item_id", "item_context", "item_reward_condition", "item_question", "item_answer", "item_continuation", "audio_file", "recording_ms", "rating", "slider_touched", "slider_moves", "replayed", "play_press_ms", "first_touch_ms", "last_touch_ms", "submit_ms", "audio_played_ms", "blur_count", "blurred_ms", "playback_stalls", "age", "gender", "handed", "lang", "caff", "study"]
  },
  validateRow: function (row) {
    var factors = window.EXP2_DESIGN.factors;
    for (var name in factors) {
      if (!Object.prototype.hasOwnProperty.call(row, name)) continue;
      var value = row[name];
      var allowed = factors[name].raw;
      if (!Object.prototype.hasOwnProperty.call(allowed, value)) {
        throw new Error(
          name + ": unexpected value not in the design: " + value
        );
      }
    }
  },
};

