// AUTO-GENERATED by `lake exe gen-js` from Design.lean.
// Do not hand-edit -- change the Lean declaration and regenerate.

window.EXP2_DESIGN = {
  factors: {
    phase: { levels: ["pretest", "test"], raw: { "pretest": "pretest", "test": "test" } },
    subexp: { levels: ["sm", "or", "wh"], raw: { "sm": "sm", "or": "or", "wh": "wh" } },
    cond_question: { levels: ["all", "no", "wh", "pos", "neg"], raw: { "all": "all", "no": "no", "wh": "wh", "pos": "pos", "neg": "neg" } },
    cond_answer: { levels: ["all", "no", "wh", "impl", "canc", "ign", "pos", "neg"], raw: { "all": "all", "no": "no", "wh": "wh", "impl": "impl", "canc": "canc", "ign": "ign", "pos": "pos", "neg": "neg" } },
    group: { levels: ["a", "b", "c", "d"], raw: { "a": "a", "b": "b", "c": "c", "d": "d" } },
    split: { levels: ["whole", "sm", "or"], raw: { "whole": "whole", "sm": "sm", "or": "or" } }
  },
  columns: {
    item: ["subexp", "condition", "cond_question", "cond_answer", "num", "kid", "group", "context", "request", "question", "answer", "audio", "q_start_ms", "q_end_ms", "a_start_ms", "a_end_ms", "total_ms"],
    results: ["session_id", "phase", "split", "session_group", "subexp", "condition", "cond_question", "cond_answer", "num", "kid", "group", "rating", "slider_touched", "time_to_first_move", "replayed", "audio_ms", "decision_time_item", "submit_time", "age", "gender", "handed", "lang", "caff", "study"]
  },
  validateRow: function (row) {
    var factors = window.EXP2_DESIGN.factors;
    for (var name in factors) {
      if (!Object.prototype.hasOwnProperty.call(row, name)) continue;
      var value = row[name];
      var allowed = factors[name].raw;
      if (!Object.prototype.hasOwnProperty.call(allowed, value)) {
        throw new Error(
          name + ": unexpected value not in the design: " + value
        );
      }
    }
  },
};

