// AUTO-GENERATED by pcibex/tools/prepare_stimuli.py from
// data/training_frame.md. Do not hand-edit -- change the prose there
// and re-run prepare_stimuli.py (--reuse-timings is enough), then build.py.
//
// One entry per screen, one string per paragraph, in order.
window.EXP2_TRAINING_FRAME = {
  "closing": [
    "Gli esempi sono finiti. Ora inizia l'esperimento vero e proprio.",
    "Alcune risposte ti sembreranno chiaramente accettabili o inaccettabili, ma per altre potresti voler dare una valutazione intermedia. Usa pure tutto l'intervallo del cursore, non solo i due estremi."
  ],
  "opening": [
    "Prima di cominciare, facciamo qualche prova insieme. Puoi ascoltare ogni dialogo al massimo due volte."
  ]
};
